Add ability to customize AppVersionCheck
sportngin/okcomputer pull request #168
Opened 2021-01-30 01:24 UTC by rmm5t

## What does it do?

- Adds ability to customize AppVersionCheck with optional `file`, `env`, and `transform` arguments.

## Related Issues

- Closes #167

2021-01-30 01:53 UTC, rmm5t commented
The build failure should be remedied after merging #170 and/or #171

2021-02-04 14:04 UTC, rmm5t commented
I'll happily rebase this branch after #170 and #171 are merged.

2021-02-04 15:24 UTC, anfleene commented
@rmm5t This is an awesome idea! Thanks for contributing it. I have a few inline concerns that I'll add in review. But the idea is solid and we've been talking about something like this for awhile and never got around to implementing it.

2021-02-04 15:28 UTC, anfleene requested changes

2021-02-04 15:28 UTC, anfleene commented on lib/ok_computer/built_in_checks/app_version_check.rb
> +    def initialize(file = "REVISION", env = "SHA", &transform)
I think I'd rather use [keyword arguments ](https://thoughtbot.com/blog/ruby-2-keyword-arguments) for this. That way the position of the argument or their existence doesn't matter. Like this:
```suggestion
    def initialize(file: "REVISION", env: "SHA", &transform)
```

2021-02-04 17:27 UTC, rmm5t commented on lib/ok_computer/built_in_checks/app_version_check.rb
> +    def initialize(file = "REVISION", env = "SHA", &transform)
@andrewschaar Agreed on the keyword args. I would have actually done that from the get-go, but it didn't look like any existing checks used them. I'll switch.

2021-02-04 18:50 UTC, rmm5t commented on lib/ok_computer/built_in_checks/app_version_check.rb
> +    def initialize(file = "REVISION", env = "SHA", &transform)
Switched to keyword args. Let me know if you'd like any other modifications. Thanks.

2021-02-04 19:25 UTC, anfleene approved these changes

2021-02-04 19:25 UTC, anfleene commented
Thanks!

2021-02-04 19:25 UTC, merged

2021-02-04 19:29 UTC, anfleene commented
[1.18.4](https://rubygems.org/gems/okcomputer/versions/1.18.4) is out with this improvement!